language: go

sudo: false

go:
  - 1.11.x
  - tip

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: tip
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

before_install:
  - go get -t -v ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
