# HTTP Request samples

# create new game
POST http://localhost:9999/games/new
Content-Type: application/json
Accept: application/json

{
  "name": "one-on-one",
  "owner": "David"
}

###

# join an existing game
POST http://localhost:9999/games/asdf/join
Content-Type: application/json
Accept: application/json

{
  "player": "Christian"
}

###

# retrieve status of game
GET http://localhost:9999/games/asdf
Accept: application/json

###

# play game
POST http://localhost:9999/games/asdf/play
Content-Type: application/json
Accept: application/json

{
  "player": "David",
  "fieldId": 0
}

###

# play game
POST http://localhost:9999/games/asdf/play
Content-Type: application/json
Accept: application/json

{
  "player": "Christian",
  "fieldId": 8
}

###

# play game
POST http://localhost:9999/games/asdf/play
Content-Type: application/json
Accept: application/json

{
  "player": "David",
  "fieldId": 3
}

###

# play game
POST http://localhost:9999/games/asdf/play
Content-Type: application/json
Accept: application/json

{
  "player": "Christian",
  "fieldId": 8
}


###

# play game
POST http://localhost:9999/games/asdf/play
Content-Type: application/json
Accept: application/json

{
  "player": "David",
  "fieldId": 6
}

###

