# HTTP Request samples

# create new game
POST http://localhost:9999/games/new
Content-Type: application/json
Accept: application/json

{
  "name": "one-on-one",
  "owner": "David"
}

###

# join an existing game
POST http://localhost:9999/games/one-on-one/join
Content-Type: application/json
Accept: application/json

{
  "player": "Christian"
}

###

# retrieve status of game
GET http://localhost:9999/games/one-on-one
Accept: application/json

###

POST http://localhost:9999/games/one-on-one/play
Content-Type: application/json
Accept: application/json

{
  "player": "David",
  "fieldId": 2
}
